title: "Rahul's blog"
description: "About algorithms, compilers, functional programming and programming lanugages."
author: "Rahul Tumpala"
url: https://rahultumpala.github.io
lang: en

# Google Analytics
google_analytics: 

github_username: "rahultumpala"
linkedin_username: "rahul-tumpala"

theme: "minima"

# rss: rss
kramdown:
  syntax_highlighter_opts:
    disable: true
permalink: /:year/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      social-share: true
      layout: post

exclude:
  - "Gemfile"
  - "Gemfile.lock"
