title: "Rahul's blog"
author: "Rahul Tumpala"
description: "A place to share my thoughts." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

github_username: "rahultumpala"
linkedin_username: "rahul-tumpala"

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true
